/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import CLASES.Logica;
import CLASES.Configuracion;
import CLASES.Empleado;
import java.awt.BorderLayout;
import java.awt.Dimension;
import java.awt.Toolkit;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author Jonathan
 */
public class Descktop extends javax.swing.JFrame {
    private Logica logica;            
    /**
     * Creates new form Descktop
     */
    public Descktop() {
        initComponents();        

        
        logica=new Logica();
        
        FrameOpcionesAdmin frame = new FrameOpcionesAdmin(logica, new Empleado(2, "JONATHAN", "ROJAS BOLLAT", true, "4321", "JONATHANRB1994@GMAIL.COM", "48366943", 2));        
        descktopPane.add(frame);
        Dimension pantalla = Toolkit.getDefaultToolkit().getScreenSize();
        Dimension ventana = frame.getSize();
        frame.setLocation((pantalla.width - ventana.width)/ 2, (pantalla.height - ventana.height)/ 2);
        frame.show();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        contribuyenteChico = new javax.swing.ButtonGroup();
        descktopPane = new javax.swing.JDesktopPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Emision de Facturas");

        descktopPane.setBackground(new java.awt.Color(142, 200, 238));

        javax.swing.GroupLayout descktopPaneLayout = new javax.swing.GroupLayout(descktopPane);
        descktopPane.setLayout(descktopPaneLayout);
        descktopPaneLayout.setHorizontalGroup(
            descktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 888, Short.MAX_VALUE)
        );
        descktopPaneLayout.setVerticalGroup(
            descktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 535, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(descktopPane)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(descktopPane)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup contribuyenteChico;
    public static javax.swing.JDesktopPane descktopPane;
    // End of variables declaration//GEN-END:variables

    
}
