/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import CLASES.Configuracion;
import CLASES.Logica;
import CLASES.ResolucionSistema;
import java.util.Date;
import javax.swing.JOptionPane;

/**
 *
 * @author Jonathan
 */
public class FrameConfiguracion extends javax.swing.JInternalFrame {
    private Configuracion dbConfig;
    private ResolucionSistema dbResSystem;
    private Logica logica;
    /**
     * Creates new form OpcionesAdmin
     */
    public FrameConfiguracion(Logica logica) {
        initComponents();
                
        this.logica=logica;
        dbConfig=logica.getConfigClass();        
        
       txNombreComercial.setText(dbConfig.getNombreComercial());
       txRazonSocial.setText(dbConfig.getRazonSocial());       
       txDireccion.setText(dbConfig.getDireccion());
       txNIT.setText(dbConfig.getNIT());
       
       dbResSystem=logica.getResSystemClass();
       
       txResolucion.setText(dbResSystem.getNoResolucion());
       dateSistema.setDate(dbResSystem.getFecha());
       txMaquina.setText(dbResSystem.getNoMaquiena()+"");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txNombreComercial = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txRazonSocial = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txNIT = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txDireccion = new javax.swing.JTextField();
        btGuardarConf = new javax.swing.JButton();
        btGuardarRes = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        txResolucion = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        dateSistema = new com.toedter.calendar.JDateChooser();
        jLabel8 = new javax.swing.JLabel();
        txMaquina = new javax.swing.JTextField();

        setClosable(true);
        setTitle("Configuracion");

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("CONFIGURACION");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel2.setText("Nombre Comercial:");

        txNombreComercial.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txNombreComercial.setNextFocusableComponent(txRazonSocial);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel3.setText("Razon Social:");

        txRazonSocial.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txRazonSocial.setNextFocusableComponent(txNIT);

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel4.setText("NIT:");

        txNIT.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txNIT.setNextFocusableComponent(txDireccion);

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel5.setText("Dirección:");

        txDireccion.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txDireccion.setNextFocusableComponent(btGuardarConf);

        btGuardarConf.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btGuardarConf.setText("Guardar");
        btGuardarConf.setNextFocusableComponent(txResolucion);
        btGuardarConf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btGuardarConfActionPerformed(evt);
            }
        });
        btGuardarConf.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btGuardarConfKeyPressed(evt);
            }
        });

        btGuardarRes.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btGuardarRes.setText("Guardar");
        btGuardarRes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btGuardarResActionPerformed(evt);
            }
        });
        btGuardarRes.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btGuardarResKeyPressed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel6.setText("Fecha de Autorización:");

        txResolucion.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txResolucion.setNextFocusableComponent(txMaquina);

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel7.setText("Resolucion");

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel11.setText("RESOLUCION DEL SISTEMA");

        dateSistema.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        dateSistema.setNextFocusableComponent(btGuardarRes);

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel8.setText("No. de Maquina:");

        txMaquina.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txMaquina.setNextFocusableComponent(dateSistema);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(94, 94, 94)
                .addComponent(btGuardarConf, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(571, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(txNombreComercial, javax.swing.GroupLayout.PREFERRED_SIZE, 352, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3)
                            .addComponent(txRazonSocial, javax.swing.GroupLayout.PREFERRED_SIZE, 352, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4)
                            .addComponent(txNIT, javax.swing.GroupLayout.PREFERRED_SIZE, 352, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5)
                            .addComponent(txDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, 352, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(136, 136, 136)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 282, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(105, 105, 105))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel6)
                                .addComponent(dateSistema, javax.swing.GroupLayout.PREFERRED_SIZE, 417, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txResolucion, javax.swing.GroupLayout.PREFERRED_SIZE, 417, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txMaquina, javax.swing.GroupLayout.PREFERRED_SIZE, 417, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(39, 39, 39))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btGuardarRes, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(151, 151, 151))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addComponent(jLabel2)
                .addGap(6, 6, 6)
                .addComponent(txNombreComercial, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addGap(6, 6, 6)
                .addComponent(txRazonSocial, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addGap(6, 6, 6)
                .addComponent(txNIT, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel5)
                .addGap(19, 19, 19)
                .addComponent(txDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btGuardarConf, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(27, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txResolucion, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txMaquina, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(dateSistema, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btGuardarRes, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(100, 100, 100))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btGuardarConfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btGuardarConfActionPerformed
        if(txNombreComercial.getText().equals("") || txRazonSocial.getText().equals("") || txDireccion.getText().equals("") || txNIT.getText().equals("")){
            JOptionPane.showMessageDialog(this, "Todos los campos de configuración son obligatorios.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        dbConfig.setNombreComercial(txNombreComercial.getText().toUpperCase());
        dbConfig.setRazonSocial(txRazonSocial.getText().toUpperCase());
        dbConfig.setDireccion(txDireccion.getText().toUpperCase());
        dbConfig.setNIT(txNIT.getText().toUpperCase());

        if( logica.updateConfiguracion(dbConfig) ){
            JOptionPane.showMessageDialog(this, "Actualizacion correcta.", "Correcto", JOptionPane.PLAIN_MESSAGE);
        }else{
            JOptionPane.showMessageDialog(this, "No se pudo actualizar la configuración.", "Error", JOptionPane.ERROR_MESSAGE);

            dbConfig = logica.getConfigClass();

            txNombreComercial.setText(dbConfig.getNombreComercial());
            txRazonSocial.setText(dbConfig.getRazonSocial());
            txDireccion.setText(dbConfig.getDireccion());
            txNIT.setText(dbConfig.getNIT());
        }
    }//GEN-LAST:event_btGuardarConfActionPerformed

    private void btGuardarResActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btGuardarResActionPerformed

        if(txResolucion.getText().equals("") || txMaquina.getText().equals("")){
            JOptionPane.showMessageDialog(this, "Todos los campos de resolución son obligatorios.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        if( new Date().compareTo(dateSistema.getDate())!=1 ){
            JOptionPane.showMessageDialog(this, "La fecha de autorizacion es mayor a la de hoy.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        
        dbResSystem.setNoResolucion(txResolucion.getText().toUpperCase());
        dbResSystem.setFecha(dateSistema.getDate());  
        dbResSystem.setNoMaquiena(Integer.valueOf(txMaquina.getText()));
        
        if( logica.updateResSystem(dbResSystem) ){
            JOptionPane.showMessageDialog(this, "Actualizacion correcta.", "Correcto", JOptionPane.PLAIN_MESSAGE);
        }else{
            JOptionPane.showMessageDialog(this, "No se pudo actualizar la resolución del sistema.", "Error", JOptionPane.ERROR_MESSAGE);

            dbResSystem=logica.getResSystemClass();
       
            txResolucion.setText(dbResSystem.getNoResolucion());
            dateSistema.setDate(dbResSystem.getFecha());
            txMaquina.setText(dbResSystem.getNoMaquiena()+"");
        }
    }//GEN-LAST:event_btGuardarResActionPerformed

    private void btGuardarConfKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btGuardarConfKeyPressed
        btGuardarConf.doClick();
    }//GEN-LAST:event_btGuardarConfKeyPressed

    private void btGuardarResKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btGuardarResKeyPressed
        btGuardarRes.doClick();
    }//GEN-LAST:event_btGuardarResKeyPressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btGuardarConf;
    private javax.swing.JButton btGuardarRes;
    private com.toedter.calendar.JDateChooser dateSistema;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JTextField txDireccion;
    private javax.swing.JTextField txMaquina;
    private javax.swing.JTextField txNIT;
    private javax.swing.JTextField txNombreComercial;
    private javax.swing.JTextField txRazonSocial;
    private javax.swing.JTextField txResolucion;
    // End of variables declaration//GEN-END:variables
}
