/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;


import CLASES.Empleado;
import CLASES.Logica;
import com.mxrck.autocompleter.TextAutoCompleter;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author Jonathan
 */
public class FrameEmpleados extends javax.swing.JInternalFrame {
    private Logica logica;
    
    private ArrayList <Empleado> empleados;    
    
    private TextAutoCompleter autoNombre;
    private TextAutoCompleter autoApellidos;
    
    private boolean habilitar=false;
    /**
     * Creates new form FrameEmpleados
     */
    public FrameEmpleados(Logica logica) {
        initComponents();
        
        this.logica=logica;
        
        actualizar();
    }

    private void actualizar(){
        String condiciones="";
        if(rbSI.isSelected()){
            condiciones+=" AND ESTADO=1 ";
        }else{
            condiciones+=" AND ESTADO=0 ";
        }
        DefaultTableModel modelo = logica.getModelEmpleados(condiciones);
        TableRowSorter sorter = new TableRowSorter(modelo);
        tableEmpleados.setModel(modelo);
        tableEmpleados.setRowSorter(sorter);
        
        txNombre.setText("");
        txApellidos.setText("");
        
        empleados=logica.getListEmpleados();
        
        autoNombre = new TextAutoCompleter(txNombre);
        autoApellidos = new TextAutoCompleter(txApellidos);
        
        autoNombre.setCaseSensitive(false);
        autoApellidos.setCaseSensitive(false);
        
        autoNombre.setMode(0);
        autoApellidos.setMode(0);

        
        for (int i = 0; i < empleados.size(); i++) {
            autoNombre.addItem(empleados.get(i).getNombre());
            autoApellidos.addItem(empleados.get(i).getApellidos());
        }
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        activo = new javax.swing.ButtonGroup();
        jLabel17 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tableEmpleados = new javax.swing.JTable();
        rbSI = new javax.swing.JRadioButton();
        rbNO = new javax.swing.JRadioButton();
        jLabel3 = new javax.swing.JLabel();
        btActualizar1 = new javax.swing.JButton();
        btEstado = new javax.swing.JButton();
        btBuscar = new javax.swing.JButton();
        btNuevo = new javax.swing.JButton();
        txApellidos = new javax.swing.JTextField();
        jlabel11 = new javax.swing.JLabel();
        txNombre = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();

        setClosable(true);
        setTitle("Empleados");

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel17.setText("EMPLEADOS");

        tableEmpleados.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        tableEmpleados.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(tableEmpleados);

        activo.add(rbSI);
        rbSI.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        rbSI.setSelected(true);
        rbSI.setText("SI");
        rbSI.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                rbSIItemStateChanged(evt);
            }
        });

        activo.add(rbNO);
        rbNO.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        rbNO.setText("NO");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel3.setText("Activo:");

        btActualizar1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btActualizar1.setText("Actualizar");
        btActualizar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btActualizar1ActionPerformed(evt);
            }
        });

        btEstado.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btEstado.setText("Deshabilitar");
        btEstado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btEstadoActionPerformed(evt);
            }
        });

        btBuscar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btBuscar.setText("Buscar");
        btBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btBuscarActionPerformed(evt);
            }
        });

        btNuevo.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btNuevo.setText("Nuevo Empleado");
        btNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btNuevoActionPerformed(evt);
            }
        });

        txApellidos.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jlabel11.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jlabel11.setText("Apellidos:");

        txNombre.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel2.setText("Nombre:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btActualizar1, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btNuevo, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 910, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jlabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txApellidos, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(10, 10, 10)
                                        .addComponent(rbSI))
                                    .addComponent(jLabel3))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(rbNO)
                                .addGap(18, 18, 18)
                                .addComponent(btBuscar)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btActualizar1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btNuevo, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addComponent(jLabel3)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(rbSI)
                                .addComponent(rbNO)))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(18, 18, 18)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addComponent(jLabel2)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(txNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addComponent(jlabel11)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(txApellidos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 335, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rbSIItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_rbSIItemStateChanged

        if(rbSI.isSelected()){
            habilitar=false;
            btEstado.setText("Deshabilitar");
        }else{
            habilitar=true;
            btEstado.setText("Habilitar");
        }
        actualizar();

    }//GEN-LAST:event_rbSIItemStateChanged

    private void btActualizar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btActualizar1ActionPerformed
        actualizar();

        txNombre.setText("");
        txApellidos.setText("");
    }//GEN-LAST:event_btActualizar1ActionPerformed

    private void btEstadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btEstadoActionPerformed
        try {
            DefaultTableModel tm = (DefaultTableModel) tableEmpleados.getModel();
            String id=String.valueOf(tm.getValueAt(tableEmpleados.getSelectedRow(),0));

            if(habilitar){
                if(logica.changeStateEmpleado(id, "1")){
                    JOptionPane.showMessageDialog(this, "Empleado "+id+" habilitado.", "Correcto", JOptionPane.PLAIN_MESSAGE);
                }else{
                    JOptionPane.showMessageDialog(this, "El empleado "+id+" no se puedo habilitar.", "Error", JOptionPane.ERROR_MESSAGE);
                }
            }else{
                if(logica.changeStateEmpleado(id, "0")){
                    JOptionPane.showMessageDialog(this, "Empleado "+id+" deshabilitado.", "Correcto", JOptionPane.PLAIN_MESSAGE);
                }else{
                    JOptionPane.showMessageDialog(this, "El empleado "+id+" no se puedo deshabilitado.", "Error", JOptionPane.ERROR_MESSAGE);
                }
            }
            actualizar();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Selecciones una fila de la tabla.", "Error", JOptionPane.ERROR_MESSAGE);
        }

    }//GEN-LAST:event_btEstadoActionPerformed

    private void btBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btBuscarActionPerformed
        String nombre="";
        String apellidos="";
        nombre+=txNombre.getText().toUpperCase();
        apellidos+=txApellidos.getText().toUpperCase();

        boolean datos=false;
        String condiciones="";
        if(rbSI.isSelected()){
            condiciones+=" AND E.ESTADO=1 ";
        }else{
            condiciones+=" AND E.ESTADO=0 ";
        }
        String mensaje="Se realizo una busqueda por ";
        if(!nombre.equals("")){
            datos=true;
            condiciones+=" AND E.NOMBRE LIKE \'%"+nombre.toUpperCase()+"%\' ";
            mensaje+="NOMBRE";
        }
        if(!apellidos.equals("")){
            datos=true;
            condiciones+=" AND E.APELLIDOS LIKE \'%"+apellidos.toUpperCase()+"%\' ";
            mensaje+=" APELIIDOS";
        }
        mensaje+=".";
        
        if(!datos){
            actualizar();
            return;
        }

        JOptionPane.showMessageDialog(this, mensaje, "Buscado", JOptionPane.PLAIN_MESSAGE);
        DefaultTableModel modelo = logica.getModelEmpleados(condiciones);
        TableRowSorter sorter = new TableRowSorter(modelo);
        tableEmpleados.setModel(modelo);
        tableEmpleados.setRowSorter(sorter);
    }//GEN-LAST:event_btBuscarActionPerformed

    private void btNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btNuevoActionPerformed
        FrameNuevoEmpleado frame = new FrameNuevoEmpleado(logica);
        Descktop.descktopPane.add(frame);
        frame.toFront();
        Dimension pantalla = Toolkit.getDefaultToolkit().getScreenSize();
        Dimension ventana = frame.getSize();
        frame.setLocation((pantalla.width - ventana.width)/ 2, (pantalla.height - ventana.height)/ 2);
        frame.show();
    }//GEN-LAST:event_btNuevoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup activo;
    private javax.swing.JButton btActualizar1;
    private javax.swing.JButton btBuscar;
    private javax.swing.JButton btEstado;
    private javax.swing.JButton btNuevo;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel jlabel11;
    private javax.swing.JRadioButton rbNO;
    private javax.swing.JRadioButton rbSI;
    private javax.swing.JTable tableEmpleados;
    private javax.swing.JTextField txApellidos;
    private javax.swing.JTextField txNombre;
    // End of variables declaration//GEN-END:variables
}
