USE FACTURACION_ANALISIS;


INSERT INTO MARCA(NOMBRE) VALUES('SAMSUNG');
INSERT INTO MARCA(NOMBRE) VALUES('XPERIA');

INSERT INTO PRODUCTO(NOMBRE) VALUES ('S6');
INSERT INTO PRODUCTO(NOMBRE) VALUES ('S8');

INSERT INTO PRESENTACION(NOMBRE) VALUES('TELEFONO');

INSERT INTO UNIDAD(NOMBRE) VALUES('UNIDAD');
INSERT INTO UNIDAD(NOMBRE) VALUES('CAJA');

INSERT INTO INVENTARIO(PRODUCTO, MARCA, PRESENTACION, UNIDAD, PRECIO) VALUES (2,1,1,1,500);



SELECT * FROM PRODUCTO;
SELECT * FROM MARCA;
SELECT * FROM PRESENTACION;
SELECT * FROM UNIDAD;
SELECT * FROM INVENTARIO;
SELECT * FROM INVENTARIO WHERE PRODUCTO IN (SELECT ID FROM PRODUCTO WHERE NOMBRE='S8');

SELECT * FROM RESOLUCION WHERE NO_RESOLUCION='123456';