/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import CLASES.Inventario;
import CLASES.Logica;
import CLASES.Marca;
import CLASES.Presentacion;
import CLASES.Producto;
import CLASES.Unidad;
import com.mxrck.autocompleter.TextAutoCompleter;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author Jonathan
 */
public class FrameNuevoArticulo extends javax.swing.JInternalFrame {
    private Logica logica;
    private TextAutoCompleter autoProducto;
    private TextAutoCompleter autoMarca;
    private TextAutoCompleter autoPresentacion;
    private TextAutoCompleter autoUnidad;
    
    private ArrayList <Producto> productos;
    private ArrayList <Marca> marcas;
    private ArrayList <Presentacion> presentaciones;
    private ArrayList <Unidad> unidades;
    /**
     * Creates new form FrameNuevoArticulo
     */
    public FrameNuevoArticulo(Logica logica) {
        initComponents();
        
        this.logica=logica;
        
        productos=logica.getListProducto();        
        autoProducto = new TextAutoCompleter(txProducto);
        autoProducto.setCaseSensitive(false);
        autoProducto.setMode(0);
        for (int i = 0; i < productos.size(); i++) {
            autoProducto.addItem(productos.get(i).getNombre());
        }
        
        marcas=logica.getListMarca();        
        autoMarca = new TextAutoCompleter(txMarca);
        autoMarca.setCaseSensitive(false);
        autoMarca.setMode(0);
        for (int i = 0; i < marcas.size(); i++) {
            autoMarca.addItem(marcas.get(i).getNombre());
        }   
        
        presentaciones=logica.getListPresentacion();        
        autoPresentacion = new TextAutoCompleter(txPresentacion);
        autoPresentacion.setCaseSensitive(false);
        autoPresentacion.setMode(0);
        for (int i = 0; i < presentaciones.size(); i++) {
            autoPresentacion.addItem(presentaciones.get(i).getNombre());
        }  
        
        unidades=logica.getListUnidad();        
        autoUnidad = new TextAutoCompleter(txUnidad);
        autoUnidad.setCaseSensitive(false);
        autoUnidad.setMode(0);
        for (int i = 0; i < unidades.size(); i++) {
            autoUnidad.addItem(unidades.get(i).getNombre());
        }  
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txProducto = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txMarca = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txPresentacion = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        txUnidad = new javax.swing.JTextField();
        Unidad1 = new javax.swing.JLabel();
        txPrecio = new javax.swing.JTextField();
        btGuardar = new javax.swing.JButton();

        setClosable(true);
        setTitle("Nuevo Articulo");

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("NUEVO ARTICULO");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel2.setText("Producto:");

        txProducto.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel3.setText("Marca:");

        txMarca.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel4.setText("Presentación:");

        txPresentacion.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel14.setText("Unidad:");

        txUnidad.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        Unidad1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        Unidad1.setText("Precio:");

        txPrecio.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        btGuardar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btGuardar.setText("Guardar");
        btGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btGuardarActionPerformed(evt);
            }
        });
        btGuardar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btGuardarKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(txProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3)
                            .addComponent(txMarca, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4)
                            .addComponent(txPresentacion, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel14)
                            .addComponent(txUnidad, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Unidad1)
                            .addComponent(txPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(74, 74, 74)
                        .addComponent(btGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1)))
                .addContainerGap(32, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txMarca, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txPresentacion, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel14)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txUnidad, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Unidad1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btGuardarActionPerformed
        
        if( txProducto.getText().equals("") || txMarca.getText().equals("") || txPresentacion.getText().equals("") || txUnidad.getText().equals("") || txPrecio.getText().equals("") ){
            JOptionPane.showMessageDialog(this, "Todos los campos del nuevo articulo son obligatorios.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        if (autoProducto.findItem(txProducto.getText()) == null ){
            if(!logica.insertReg(txProducto.getText().toUpperCase(), "PRODUCTO")){
                JOptionPane.showMessageDialog(this, "No se puedo crear el nuevo producto.", "Error", JOptionPane.ERROR_MESSAGE);
                return;
            }
        }
        
        if (autoMarca.findItem(txMarca.getText()) == null ){
            if(!logica.insertReg(txMarca.getText().toUpperCase(), "MARCA")){
                JOptionPane.showMessageDialog(this, "No se puedo crear la nueva marca.", "Error", JOptionPane.ERROR_MESSAGE);
                return;
            }
        }
        
        if (autoPresentacion.findItem(txPresentacion.getText()) == null ){
            if(!logica.insertReg(txPresentacion.getText().toUpperCase(), "PRESENTACION")){
                JOptionPane.showMessageDialog(this, "No se puedo crear la nueva presentación.", "Error", JOptionPane.ERROR_MESSAGE);
                return;
            }
        }
        
        if (autoUnidad.findItem(txUnidad.getText()) == null ){
            if(!logica.insertReg(txUnidad.getText().toUpperCase(), "UNIDAD")){
                JOptionPane.showMessageDialog(this, "No se puedo crear la nueva unidad.", "Error", JOptionPane.ERROR_MESSAGE);
                return;
            }
        }
        System.out.println(Double.valueOf(txPrecio.getText()));
        
        if(!logica.insertArticulo( new Inventario(txProducto.getText().toUpperCase(), txMarca.getText().toUpperCase(), txPresentacion.getText().toUpperCase(), txUnidad.getText().toUpperCase(), Double.valueOf(txPrecio.getText())) )){
            JOptionPane.showMessageDialog(this, "No se puedo agregar el articulo, puede que ya exista.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }else{
            JOptionPane.showMessageDialog(this, "Articulo agregado.", "Correcto", JOptionPane.PLAIN_MESSAGE);
            this.dispose();;
        }

        
        
    }//GEN-LAST:event_btGuardarActionPerformed

    private void btGuardarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btGuardarKeyPressed
        btGuardar.doClick();
    }//GEN-LAST:event_btGuardarKeyPressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Unidad1;
    private javax.swing.JButton btGuardar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField txMarca;
    private javax.swing.JTextField txPrecio;
    private javax.swing.JTextField txPresentacion;
    private javax.swing.JTextField txProducto;
    private javax.swing.JTextField txUnidad;
    // End of variables declaration//GEN-END:variables
}
