/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import CLASES.Configuracion;
import CLASES.Empleado;
import CLASES.Logica;
import java.awt.BorderLayout;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.util.Date;
import javax.swing.JOptionPane;

/**
 *
 * @author Jonathan
 */
public class FrameOpcionesAdmin extends javax.swing.JInternalFrame {
    private Logica logica;
    private Empleado empleado;
    /**
     * Creates new form FrameOpcionesAdmin
     */
    public FrameOpcionesAdmin(Logica logica, Empleado empleado) {
        initComponents();
        this.logica=logica;  
        this.empleado=empleado;
        
        if(!logica.checkResolution("FACTURA")){
            JOptionPane.showMessageDialog(this, "No cuenta con resoluciones de tipo FACTURA", "ERROR", JOptionPane.ERROR_MESSAGE);
        }
        if(!logica.checkResolution("NOTA DEBITO")){
            JOptionPane.showMessageDialog(this, "No cuenta con resoluciones de tipo NOTA DEBITO", "ERROR", JOptionPane.ERROR_MESSAGE);
        }
        if(!logica.checkResolution("NOTA CREDITO")){
            JOptionPane.showMessageDialog(this, "No cuenta con resoluciones de tipo NOTA CREDITO", "ERROR", JOptionPane.ERROR_MESSAGE);
        }
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btClientes = new javax.swing.JButton();
        btVenta = new javax.swing.JButton();
        btInventario = new javax.swing.JButton();
        btCompra = new javax.swing.JButton();
        btTransacciones = new javax.swing.JButton();
        btEmpleados = new javax.swing.JButton();
        btResoluciones = new javax.swing.JButton();
        btConfiguracion = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setClosable(true);
        setTitle("Opciones");

        btClientes.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btClientes.setText("CLIENTES");
        btClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btClientesActionPerformed(evt);
            }
        });
        btClientes.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                btClientesKeyReleased(evt);
            }
        });

        btVenta.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btVenta.setText("VENTA");
        btVenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btVentaActionPerformed(evt);
            }
        });
        btVenta.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btVentaKeyPressed(evt);
            }
        });

        btInventario.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btInventario.setText("INVENTARIO");
        btInventario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btInventarioActionPerformed(evt);
            }
        });
        btInventario.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btInventarioKeyPressed(evt);
            }
        });

        btCompra.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btCompra.setText("COMPRA");
        btCompra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCompraActionPerformed(evt);
            }
        });
        btCompra.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btCompraKeyPressed(evt);
            }
        });

        btTransacciones.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btTransacciones.setText("TRANSACCIONES");
        btTransacciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btTransaccionesActionPerformed(evt);
            }
        });
        btTransacciones.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btTransaccionesKeyPressed(evt);
            }
        });

        btEmpleados.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btEmpleados.setText("EMPLEADOS");
        btEmpleados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btEmpleadosActionPerformed(evt);
            }
        });
        btEmpleados.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btEmpleadosKeyPressed(evt);
            }
        });

        btResoluciones.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btResoluciones.setText("RESOLUCIONES");
        btResoluciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btResolucionesActionPerformed(evt);
            }
        });
        btResoluciones.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btResolucionesKeyPressed(evt);
            }
        });

        btConfiguracion.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btConfiguracion.setText("CONFIGURACION");
        btConfiguracion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btConfiguracionActionPerformed(evt);
            }
        });
        btConfiguracion.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btConfiguracionKeyPressed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("OPCIONES ADMINISTRADOR");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(232, 232, 232)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 303, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btClientes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btTransacciones, javax.swing.GroupLayout.DEFAULT_SIZE, 172, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btVenta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btEmpleados, javax.swing.GroupLayout.DEFAULT_SIZE, 182, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btResoluciones, javax.swing.GroupLayout.DEFAULT_SIZE, 172, Short.MAX_VALUE)
                            .addComponent(btInventario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btConfiguracion, javax.swing.GroupLayout.DEFAULT_SIZE, 172, Short.MAX_VALUE)
                            .addComponent(btCompra, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(71, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btClientes, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btVenta, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btInventario, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btCompra, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(47, 47, 47)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btTransacciones, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btEmpleados, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btResoluciones, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btConfiguracion, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(37, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btConfiguracionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btConfiguracionActionPerformed
       FrameConfiguracion frame = new FrameConfiguracion(logica);       
       Descktop.descktopPane.add(frame);
       frame.toFront(); 
       Dimension pantalla = Toolkit.getDefaultToolkit().getScreenSize();
       Dimension ventana = frame.getSize();
       frame.setLocation((pantalla.width - ventana.width)/ 2, (pantalla.height - ventana.height)/ 2);
       frame.show();
    }//GEN-LAST:event_btConfiguracionActionPerformed

    private void btResolucionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btResolucionesActionPerformed
       FrameResolucion frame = new FrameResolucion(logica);       
       Descktop.descktopPane.add(frame);
       frame.toFront();  
       Dimension pantalla = Toolkit.getDefaultToolkit().getScreenSize();
       Dimension ventana = frame.getSize();
       frame.setLocation((pantalla.width - ventana.width)/ 2, (pantalla.height - ventana.height)/ 2);
       frame.show();
    }//GEN-LAST:event_btResolucionesActionPerformed

    private void btEmpleadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btEmpleadosActionPerformed
       FrameEmpleados frame = new FrameEmpleados(logica);       
       Descktop.descktopPane.add(frame);
       frame.toFront();  
       Dimension pantalla = Toolkit.getDefaultToolkit().getScreenSize();
       Dimension ventana = frame.getSize();
       frame.setLocation((pantalla.width - ventana.width)/ 2, (pantalla.height - ventana.height)/ 2);
       frame.show();
    }//GEN-LAST:event_btEmpleadosActionPerformed

    private void btTransaccionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btTransaccionesActionPerformed
        FrameTransaccion frame = new FrameTransaccion(logica);       
        Descktop.descktopPane.add(frame);
        frame.toFront();  
        Dimension pantalla = Toolkit.getDefaultToolkit().getScreenSize();
        Dimension ventana = frame.getSize();
        frame.setLocation((pantalla.width - ventana.width)/ 2, (pantalla.height - ventana.height)/ 2);
        frame.show();
    }//GEN-LAST:event_btTransaccionesActionPerformed

    private void btClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btClientesActionPerformed
        FrameClientes frame = new FrameClientes(logica);       
        Descktop.descktopPane.add(frame);
        frame.toFront(); 
        Dimension pantalla = Toolkit.getDefaultToolkit().getScreenSize();
        Dimension ventana = frame.getSize();
        frame.setLocation((pantalla.width - ventana.width)/ 2, (pantalla.height - ventana.height)/ 2);
        frame.show();
    }//GEN-LAST:event_btClientesActionPerformed

    private void btInventarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btInventarioActionPerformed
        FrameInventario frame = new FrameInventario(logica);       
        Descktop.descktopPane.add(frame);
        frame.toFront();         
        Dimension pantalla = Toolkit.getDefaultToolkit().getScreenSize();
        Dimension ventana = frame.getSize();
        frame.setLocation((pantalla.width - ventana.width)/ 2, (pantalla.height - ventana.height)/ 2);
        frame.show();
    }//GEN-LAST:event_btInventarioActionPerformed

    private void btVentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btVentaActionPerformed
        FrameVenta frame = new FrameVenta(logica, empleado);       
        Descktop.descktopPane.add(frame);
        frame.toFront(); 
        Dimension pantalla = Toolkit.getDefaultToolkit().getScreenSize();
        Dimension ventana = frame.getSize();
        frame.setLocation((pantalla.width - ventana.width)/ 2, (pantalla.height - ventana.height)/ 2);
        frame.show();
    }//GEN-LAST:event_btVentaActionPerformed

    private void btClientesKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btClientesKeyReleased

    }//GEN-LAST:event_btClientesKeyReleased

    private void btVentaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btVentaKeyPressed

    }//GEN-LAST:event_btVentaKeyPressed

    private void btInventarioKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btInventarioKeyPressed
        
    }//GEN-LAST:event_btInventarioKeyPressed

    private void btCompraKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btCompraKeyPressed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_btCompraKeyPressed

    private void btTransaccionesKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btTransaccionesKeyPressed
        // TODO add your handling code here:
        
                
    }//GEN-LAST:event_btTransaccionesKeyPressed

    private void btEmpleadosKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btEmpleadosKeyPressed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_btEmpleadosKeyPressed

    private void btResolucionesKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btResolucionesKeyPressed
        // TODO add your handling code here:                
    }//GEN-LAST:event_btResolucionesKeyPressed

    private void btConfiguracionKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btConfiguracionKeyPressed
        
    }//GEN-LAST:event_btConfiguracionKeyPressed

    private void btCompraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCompraActionPerformed
        FrameCompra frame = new FrameCompra(logica, empleado);       
        Descktop.descktopPane.add(frame);
        frame.toFront(); 
        Dimension pantalla = Toolkit.getDefaultToolkit().getScreenSize();
        Dimension ventana = frame.getSize();
        frame.setLocation((pantalla.width - ventana.width)/ 2, (pantalla.height - ventana.height)/ 2);
        frame.show();
    }//GEN-LAST:event_btCompraActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btClientes;
    private javax.swing.JButton btCompra;
    private javax.swing.JButton btConfiguracion;
    private javax.swing.JButton btEmpleados;
    private javax.swing.JButton btInventario;
    private javax.swing.JButton btResoluciones;
    private javax.swing.JButton btTransacciones;
    private javax.swing.JButton btVenta;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
